[package]
name = "pgConnect"
version = "0.1.0"
authors = ["Rosehsu <rosehsu47@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
postgres = "0.17.2"